[[bin]]
name = "app"
path = "src/main.rs"

[package]
name = "rust-rocket"
version = "0.1.0"
authors = ["jackyzha0 <j.zhao2k19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"